report:
  title: Deployment Board Insight
  output_filename: Deployment-Board-Insight.html

sections:
  - id: deployment_board_insight
    options:
      board_text_path: ./deployment_board_input.txt
      as_of_date: "2026-04-15"
      strip_days: 5
