from __future__ import annotations

"""Generate provisional NinjaTrader Strategy Analyzer seed templates.

User-saved Strategy Analyzer templates remain the best source of truth because
NinjaTrader XML can carry platform-specific serialization details. This module
creates a bootstrap template for generated strategies so the autonomous loop can
move from compile-clean source to a first optimizer plan without hand authoring
XML.
"""

import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Sequence
from xml.sax.saxutils import escape


@dataclass(frozen=True)
class StrategyParameter:
    name: str
    type_name: str
    default: str
    minimum: str
    maximum: str
    increment: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass(frozen=True)
class GeneratedSeedTemplate:
    strategy_name: str
    path: str
    parameter_count: int
    swept_parameter_count: int
    warning: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


class SeedTemplateError(RuntimeError):
    pass


def generate_seed_template_from_source(
    source_path: str | Path,
    output_path: str | Path,
    *,
    strategy_name: str | None = None,
    instrument: str = "NQ 06-26",
    optimizer_type: str = "NinjaTrader.NinjaScript.Optimizers.DefaultOptimizer",
    optimization_fitness: str = "NinjaTrader.NinjaScript.OptimizationFitnesses.MaxNetProfit",
    keep_best_results: int = 500,
    from_date: str = "2026-04-14T00:00:00",
    to_date: str = "2026-05-14T00:00:00",
) -> GeneratedSeedTemplate:
    source = Path(source_path)
    if not source.is_file():
        raise SeedTemplateError(f"Strategy source not found: {source}")
    text = source.read_text(encoding="utf-8-sig", errors="replace")
    name = strategy_name or _detect_strategy_name(text) or source.stem
    parameters = extract_strategy_parameters(text)
    if not parameters:
        raise SeedTemplateError(f"No NinjaScriptProperty parameters found in {source}")

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        render_seed_template(
            strategy_name=name,
            parameters=parameters,
            instrument=instrument,
            optimizer_type=optimizer_type,
            optimization_fitness=optimization_fitness,
            keep_best_results=keep_best_results,
            from_date=from_date,
            to_date=to_date,
        ),
        encoding="utf-8",
    )
    return GeneratedSeedTemplate(
        strategy_name=name,
        path=str(destination.resolve()),
        parameter_count=len(parameters),
        swept_parameter_count=sum(1 for parameter in parameters if parameter.minimum != parameter.maximum),
        warning=(
            "Generated bootstrap seed. Prefer replacing it with a NinjaTrader-saved "
            "Strategy Analyzer template before serious optimization."
        ),
    )


def extract_strategy_parameters(source_text: str) -> list[StrategyParameter]:
    defaults = _state_setdefaults(source_text)
    declarations = re.finditer(
        r"\[NinjaScriptProperty\](?P<attrs>.*?)(?:public)\s+"
        r"(?P<type>[A-Za-z_][A-Za-z0-9_<>.?]*)\s+"
        r"(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*\{\s*get;\s*set;\s*\}",
        source_text,
        re.DOTALL,
    )
    parameters: list[StrategyParameter] = []
    for match in declarations:
        type_name = match.group("type").strip()
        name = match.group("name").strip()
        default = defaults.get(name) or _default_for_type(type_name)
        range_values = _range_values(match.group("attrs"))
        minimum, maximum = _bounded_sweep(default, type_name, range_values)
        increment = _increment_for_type(type_name, minimum, maximum)
        parameters.append(
            StrategyParameter(
                name=name,
                type_name=_dotnet_type(type_name),
                default=_serialize(default, type_name),
                minimum=_serialize(minimum, type_name),
                maximum=_serialize(maximum, type_name),
                increment=increment,
            )
        )
    return parameters


def render_seed_template(
    *,
    strategy_name: str,
    parameters: Sequence[StrategyParameter],
    instrument: str,
    optimizer_type: str,
    optimization_fitness: str,
    keep_best_results: int,
    from_date: str,
    to_date: str,
) -> str:
    strategy_values = "\n".join(
        f"      <{escape(parameter.name)}>{escape(_strategy_value(parameter.default))}</{escape(parameter.name)}>"
        for parameter in parameters
    )
    optimizer_parameters = "\n".join(_parameter_xml(parameter) for parameter in parameters)
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by ta_foundation.nt_strategy_loop.seed_template. Replace with a NinjaTrader-saved seed for production optimization. -->
<NinjaTrader>
  <StrategyType>NinjaTrader.NinjaScript.Strategies.{escape(strategy_name)}</StrategyType>
  <BacktestType>Optimize</BacktestType>
  <OptimizerType>{escape(optimizer_type)}</OptimizerType>
  <OptimizationFitness>{escape(optimization_fitness)}</OptimizationFitness>
  <Strategy>
    <{escape(strategy_name)}>
      <BarsPeriodSerializable>
        <BarsPeriodTypeSerialize>4</BarsPeriodTypeSerialize>
        <BaseBarsPeriodType>Minute</BaseBarsPeriodType>
        <BaseBarsPeriodValue>1</BaseBarsPeriodValue>
        <Value>1</Value>
        <Value2>1</Value2>
      </BarsPeriodSerializable>
      <BarsToLoad>0</BarsToLoad>
      <From>{escape(from_date)}</From>
      <InstrumentOrInstrumentList>{escape(instrument)}</InstrumentOrInstrumentList>
      <To>{escape(to_date)}</To>
{strategy_values}
    </{escape(strategy_name)}>
  </Strategy>
  <OptimizerParameters>
    <ParameterWrapper>
      <Name>KeepBestResults</Name>
      <Value>{int(keep_best_results)}</Value>
    </ParameterWrapper>
  </OptimizerParameters>
  <OptimizationParameters>
    <ArrayOfParameter>
{optimizer_parameters}
    </ArrayOfParameter>
  </OptimizationParameters>
</NinjaTrader>
"""


def _parameter_xml(parameter: StrategyParameter) -> str:
    type_name = escape(parameter.type_name)
    return f"""      <Parameter>
        <Name>{escape(parameter.name)}</Name>
        <Min>{escape(parameter.minimum)}</Min>
        <Max>{escape(parameter.maximum)}</Max>
        <Increment>{escape(parameter.increment)}</Increment>
        <ValueSerializable>{escape(parameter.default)}</ValueSerializable>
        <ParameterTypeSerializable>{type_name}</ParameterTypeSerializable>
      </Parameter>"""


def _detect_strategy_name(source_text: str) -> str:
    match = re.search(r"\bclass\s+([A-Za-z_][A-Za-z0-9_]*)\s*:\s*Strategy\b", source_text)
    return match.group(1) if match else ""


def _state_setdefaults(source_text: str) -> dict[str, str]:
    match = re.search(
        r"if\s*\(\s*State\s*==\s*State\.SetDefaults\s*\)\s*\{(?P<body>.*?)\n\s*\}",
        source_text,
        re.DOTALL,
    )
    if not match:
        return {}
    defaults: dict[str, str] = {}
    for assignment in re.finditer(
        r"\b(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*=\s*(?P<value>[^;]+);",
        match.group("body"),
    ):
        defaults[assignment.group("name")] = assignment.group("value").strip().strip('"')
    return defaults


def _range_values(attrs: str) -> tuple[str, str] | None:
    match = re.search(r"\[Range\s*\(\s*([^,\)]+)\s*,\s*([^\)]+)\)\s*\]", attrs)
    if not match:
        return None
    return match.group(1).strip(), match.group(2).strip()


def _bounded_sweep(default: str, type_name: str, range_values: tuple[str, str] | None) -> tuple[str, str]:
    lowered = type_name.lower()
    if lowered in {"bool", "boolean", "system.boolean"}:
        return "false", "true"
    if range_values is None:
        return default, default
    if lowered in {"int", "long", "short", "system.int32", "system.int64", "system.int16"}:
        try:
            value = int(float(default))
            low = int(float(range_values[0]))
            high = int(float(range_values[1]))
        except ValueError:
            return default, default
        return str(max(low, value - 1)), str(min(high, value + 1))
    if lowered in {"double", "float", "decimal", "system.double", "system.single", "system.decimal"}:
        try:
            value = float(default)
            low = float(range_values[0])
            high = float(range_values[1])
        except ValueError:
            return default, default
        return format(max(low, value - 1.0), "g"), format(min(high, value + 1.0), "g")
    return default, default


def _default_for_type(type_name: str) -> str:
    lowered = type_name.lower()
    if lowered in {"bool", "boolean", "system.boolean"}:
        return "false"
    if lowered in {"double", "float", "decimal", "system.double", "system.single", "system.decimal"}:
        return "0.0"
    if lowered in {"int", "long", "short", "system.int32", "system.int64", "system.int16"}:
        return "0"
    return ""


def _increment_for_type(type_name: str, minimum: str, maximum: str) -> str:
    lowered = type_name.lower()
    if lowered in {"bool", "boolean", "system.boolean"}:
        return "1"
    if lowered in {"double", "float", "decimal", "system.double", "system.single", "system.decimal"}:
        return "1"
    return "1" if minimum != maximum else "1"


def _dotnet_type(type_name: str) -> str:
    lowered = type_name.lower()
    mapping = {
        "bool": "System.Boolean",
        "boolean": "System.Boolean",
        "int": "System.Int32",
        "long": "System.Int64",
        "short": "System.Int16",
        "double": "System.Double",
        "float": "System.Single",
        "decimal": "System.Decimal",
        "string": "System.String",
    }
    return mapping.get(lowered, type_name)


def _serialize(value: str, type_name: str) -> str:
    lowered = type_name.lower()
    text = str(value).strip()
    if lowered in {"bool", "boolean", "system.boolean"}:
        return "true" if text.lower() in {"true", "1", "yes"} else "false"
    return text


def _strategy_value(value: str) -> str:
    if value in {"True", "False"}:
        return value.lower()
    return value
