import os
import re

# XML Template builder
def build_nt_xml(params, strategy_name, reasoning):
    def e(tag, val):
        if isinstance(val, bool):
            val_str = "true" if val else "false"
        elif isinstance(val, float):
            val_str = f"{val:.4f}".rstrip("0").rstrip(".")
        else:
            val_str = str(val)
        return f"      <{tag}>{val_str}</{tag}>"

    notes_lines = ["      <!-- Auto-generated by ta_foundation Strategy Discovery"]
    notes_lines.append(f"           Edge: {strategy_name}")
    for key, reason in reasoning.items():
        notes_lines.append(f"           {key}: {reason}")
    notes_lines.append("      -->")
    notes_block = "\n".join(notes_lines)

    xml = f"""<?xml version="1.0" encoding="utf-8"?>
<StrategyTemplate>
  <StrategyType>NinjaTrader.NinjaScript.Strategies.StrategyDiscoveryFilter</StrategyType>
  <Strategy>
    <StrategyDiscoveryFilter xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <IsVisible>true</IsVisible>
      <calculate2>OnBarClose</calculate2>
      <AreLinesConfigurable>true</AreLinesConfigurable>
      <ArePlotsConfigurable>true</ArePlotsConfigurable>
      <BarsPeriodSerializable>
        <BarsPeriodTypeSerialize>4</BarsPeriodTypeSerialize>
        <BaseBarsPeriodType>Minute</BaseBarsPeriodType>
        <BaseBarsPeriodValue>1</BaseBarsPeriodValue>
        <VolumetricDeltaType>BidAsk</VolumetricDeltaType>
        <MarketDataType>Last</MarketDataType>
        <PointAndFigurePriceType>Close</PointAndFigurePriceType>
        <ReversalType>Tick</ReversalType>
        <Value>1</Value>
        <Value2>1</Value2>
      </BarsPeriodSerializable>
      <BarsToLoad>0</BarsToLoad>
      <Calculate>OnBarClose</Calculate>
      <Displacement>0</Displacement>
      <DisplayInDataBox>true</DisplayInDataBox>
      <From>2026-01-05T00:00:00</From>
      <IsAutoScale>true</IsAutoScale>
      <Lines />
      <MaximumBarsLookBack>TwoHundredFiftySix</MaximumBarsLookBack>
      <Name>StrategyDiscoveryFilter</Name>
      <Panel>-1</Panel>
      <Plots />
      <ScaleJustification>Right</ScaleJustification>
      <ShowTransparentPlotsInDataBox>false</ShowTransparentPlotsInDataBox>
      <To>2026-03-26T00:00:00</To>
      <IsDataSeriesRequired>true</IsDataSeriesRequired>
      <IsOverlay>true</IsOverlay>
      <SelectedValueSeries>0</SelectedValueSeries>
      <Gtd>1800-01-01T00:00:00</Gtd>
      <Template />
      <TimeInForce>Gtc</TimeInForce>
      <BacktestCommissionTemplate />
      <BarsPeriodParameter>
        <Increment>1</Increment>
        <Max xsi:type="xsd:int">0</Max>
        <Min xsi:type="xsd:int">0</Min>
        <Name />
        <ParameterTypeSerializable>System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ParameterTypeSerializable>
        <ValueSerializable>0</ValueSerializable>
      </BarsPeriodParameter>
      <BarsRequiredToTrade>50</BarsRequiredToTrade>
      <Category>Backtest</Category>
      <ConnectionLossHandling>Recalculate</ConnectionLossHandling>
      <DaysToLoad>5</DaysToLoad>
      <DefaultQuantity>{params["Contracts"]}</DefaultQuantity>
      <DisconnectDelaySeconds>10</DisconnectDelaySeconds>
      <EntriesPerDirection>1</EntriesPerDirection>
      <EntryHandling>AllEntries</EntryHandling>
      <ExitOnSessionCloseSeconds>30</ExitOnSessionCloseSeconds>
      <IncludeCommission>false</IncludeCommission>
      <InstrumentOrInstrumentList>NQ 06-26</InstrumentOrInstrumentList>
      <IsAggregated>false</IsAggregated>
      <IsExitOnSessionCloseStrategy>true</IsExitOnSessionCloseStrategy>
      <IsFillLimitOnTouch>false</IsFillLimitOnTouch>
      <IsOptimizeDataSeries>false</IsOptimizeDataSeries>
      <IsStableSession>true</IsStableSession>
      <IsTickReplay>false</IsTickReplay>
      <IsTradingHoursBreakLineVisible>true</IsTradingHoursBreakLineVisible>
      <IsWaitUntilFlat>false</IsWaitUntilFlat>
      <NumberRestartAttempts>4</NumberRestartAttempts>
      <OptimizationPeriod>10</OptimizationPeriod>
      <OrderFillResolution>Standard</OrderFillResolution>
      <OrderFillResolutionType>Minute</OrderFillResolutionType>
      <OrderFillResolutionValue>1</OrderFillResolutionValue>
      <RestartsWithinMinutes>5</RestartsWithinMinutes>
      <SetOrderQuantity>Strategy</SetOrderQuantity>
      <Slippage>0</Slippage>
      <StartBehavior>WaitUntilFlat</StartBehavior>
      <StopTargetHandling>PerEntryExecution</StopTargetHandling>
      <SupportsOptimizationGraph>true</SupportsOptimizationGraph>
      <TestPeriod>28</TestPeriod>
      <TradingHoursSerializable />
      <DrawOnPricePanel>false</DrawOnPricePanel>
      <ZOrder>-2147483648</ZOrder>
{notes_block}
{e("RegimeMode", params["RegimeMode"])}
{e("AdxPeriod", params["AdxPeriod"])}
{e("AdxThreshold", params["AdxThreshold"])}
{e("RegimeEmaPeriod", params["RegimeEmaPeriod"])}
{e("AtrPeriod", params["AtrPeriod"])}
{e("AtrLookbackBars", params["AtrLookbackBars"])}
{e("VolLowPercentile", params["VolLowPercentile"])}
{e("VolHighPercentile", params["VolHighPercentile"])}
{e("AllowRTH", params["AllowRTH"])}
{e("AllowONH", params["AllowONH"])}
{e("AllowETH", params["AllowETH"])}
{e("RthStartH", params["RthStartH"])}
{e("RthStartM", params["RthStartM"])}
{e("RthEndH", params["RthEndH"])}
{e("RthEndM", params["RthEndM"])}
{e("EthStartH", params["EthStartH"])}
{e("EthStartM", params["EthStartM"])}
{e("EthEndH", params["EthEndH"])}
{e("EthEndM", params["EthEndM"])}
{e("AllowLong", params["AllowLong"])}
{e("AllowShort", params["AllowShort"])}
{e("UseTrendAlignment", params["UseTrendAlignment"])}
{e("EntryEmaPeriod", params["EntryEmaPeriod"])}
{e("SlowEmaPeriod", params["SlowEmaPeriod"])}
{e("RequireEmaConfirmation", params["RequireEmaConfirmation"])}
{e("RequireMinAtrMultiple", params["RequireMinAtrMultiple"])}
{e("ExitPolicy", params["ExitPolicy"])}
{e("StopTicks", params["StopTicks"])}
{e("TargetTicks", params["TargetTicks"])}
{e("AtrTrailMultiple", params["AtrTrailMultiple"])}
{e("ChandelierLookback", params["ChandelierLookback"])}
{e("GivebackPct", params["GivebackPct"])}
{e("BreakEvenTriggerTicks", params["BreakEvenTriggerTicks"])}
{e("BreakEvenPlusTicks", params["BreakEvenPlusTicks"])}
{e("MaxDailyLossUsd", params["MaxDailyLossUsd"])}
{e("MaxDailyProfitUsd", params["MaxDailyProfitUsd"])}
{e("MaxDailyTrades", params["MaxDailyTrades"])}
{e("EnableDebugPrint", params["EnableDebugPrint"])}
{e("Contracts", params["Contracts"])}
    </StrategyDiscoveryFilter>
  </Strategy>
</StrategyTemplate>
"""
    return xml

# Main execution
def main():
    target_dir = r"d:\Backup\projects\PythonProject\ta_foundation\docs\reports_documentation\ninja_trader_templates"
    os.makedirs(target_dir, exist_ok=True)
    print(f"Creating templates in: {target_dir}")

    # 1. Volatility Breakout (Regime Scoped to High Vol Expansion)
    vb_params = {
        "RegimeMode": "HighVolOnly",
        "AdxPeriod": 14,
        "AdxThreshold": 25,
        "RegimeEmaPeriod": 50,
        "AtrPeriod": 14,
        "AtrLookbackBars": 100,
        "VolLowPercentile": 0.3,
        "VolHighPercentile": 0.7,
        "AllowRTH": True,
        "AllowONH": True,
        "AllowETH": True,
        "RthStartH": 8,
        "RthStartM": 30,
        "RthEndH": 15,
        "RthEndM": 0,
        "EthStartH": 7,
        "EthStartM": 0,
        "EthEndH": 8,
        "EthEndM": 29,
        "AllowLong": True,
        "AllowShort": True,
        "UseTrendAlignment": True,
        "EntryEmaPeriod": 5,
        "SlowEmaPeriod": 200,
        "RequireEmaConfirmation": True,
        "RequireMinAtrMultiple": 0,
        "ExitPolicy": "AtrTrail",
        "StopTicks": 534,
        "TargetTicks": 938,
        "AtrTrailMultiple": 1.0,
        "ChandelierLookback": 20,
        "GivebackPct": 0.40,
        "BreakEvenTriggerTicks": 267,
        "BreakEvenPlusTicks": 4,
        "MaxDailyLossUsd": 2670,
        "MaxDailyProfitUsd": 8000,
        "MaxDailyTrades": 3,
        "EnableDebugPrint": False,
        "Contracts": 1
    }
    vb_reasoning = {
        "RegimeMode": "HighVolOnly — strictly scoped to high volatility days to maximize breakout magnitude",
        "AdxThreshold": "25 — requires trend momentum confirmation",
        "StopTicks": "534 ticks ($2,670) — p75 MAE of winners under high volatility expansion",
        "TargetTicks": "938 ticks ($4,690) — p50 MFE of winners under high volatility expansion",
        "ExitPolicy": "AtrTrail — trails with standard volatility ATR band",
        "MaxDailyLossUsd": "2670 — capped at one full trade loss value to protect account capital"
    }
    vb_xml = build_nt_xml(vb_params, "Volatility Breakout (High Vol Expansion Scoped)", vb_reasoning)
    with open(os.path.join(target_dir, "Volatility_Breakout_High_Vol_Edge.xml"), "w", encoding="utf-8") as f:
        f.write(vb_xml)
    print("Saved Volatility_Breakout_High_Vol_Edge.xml")

    # 2. Swing Level Breakout (Ranging Wide Scoped)
    sl_params = {
        "RegimeMode": "RangingOnly",
        "AdxPeriod": 14,
        "AdxThreshold": 25,
        "RegimeEmaPeriod": 50,
        "AtrPeriod": 14,
        "AtrLookbackBars": 100,
        "VolLowPercentile": 0.3,
        "VolHighPercentile": 0.7,
        "AllowRTH": True,
        "AllowONH": True,
        "AllowETH": True,
        "RthStartH": 8,
        "RthStartM": 30,
        "RthEndH": 15,
        "RthEndM": 0,
        "EthStartH": 7,
        "EthStartM": 0,
        "EthEndH": 8,
        "EthEndM": 29,
        "AllowLong": True,
        "AllowShort": True,
        "UseTrendAlignment": True,
        "EntryEmaPeriod": 5,
        "SlowEmaPeriod": 200,
        "RequireEmaConfirmation": True,
        "RequireMinAtrMultiple": 0,
        "ExitPolicy": "AtrTrail",
        "StopTicks": 245,
        "TargetTicks": 536,
        "AtrTrailMultiple": 1.0,
        "ChandelierLookback": 20,
        "GivebackPct": 0.40,
        "BreakEvenTriggerTicks": 122,
        "BreakEvenPlusTicks": 4,
        "MaxDailyLossUsd": 1227,
        "MaxDailyProfitUsd": 3680,
        "MaxDailyTrades": 5,
        "EnableDebugPrint": False,
        "Contracts": 1
    }
    sl_reasoning = {
        "RegimeMode": "RangingOnly — scoped strictly to ranging days to capture pivot extremes without trend overrun",
        "StopTicks": "245 ticks ($1,225) — p75 MAE of winners during pivot extreme test",
        "TargetTicks": "536 ticks ($2,680) — p50 MFE of winners",
        "ExitPolicy": "AtrTrail — trails with standard volatility ATR band",
        "MaxDailyLossUsd": "1227 — capped at one full trade loss to protect capital"
    }
    sl_xml = build_nt_xml(sl_params, "Swing Level Breakout (Ranging Wide Scoped)", sl_reasoning)
    with open(os.path.join(target_dir, "Swing_Level_Breakout_Ranging_Edge.xml"), "w", encoding="utf-8") as f:
        f.write(sl_xml)
    print("Saved Swing_Level_Breakout_Ranging_Edge.xml")

    # 3. Prior Session Reaction Close Scalp
    ps_params = {
        "RegimeMode": "Any",
        "AdxPeriod": 14,
        "AdxThreshold": 20,
        "RegimeEmaPeriod": 50,
        "AtrPeriod": 14,
        "AtrLookbackBars": 100,
        "VolLowPercentile": 0.3,
        "VolHighPercentile": 0.7,
        "AllowRTH": True,
        "AllowONH": False,
        "AllowETH": False,
        "RthStartH": 7,
        "RthStartM": 30,
        "RthEndH": 16,
        "RthEndM": 0,
        "EthStartH": 7,
        "EthStartM": 0,
        "EthEndH": 8,
        "EthEndM": 29,
        "AllowLong": True,
        "AllowShort": True,
        "UseTrendAlignment": True,
        "EntryEmaPeriod": 5,
        "SlowEmaPeriod": 200,
        "RequireEmaConfirmation": True,
        "RequireMinAtrMultiple": 0,
        "ExitPolicy": "FixedRR",
        "StopTicks": 8,
        "TargetTicks": 20,
        "AtrTrailMultiple": 1.0,
        "ChandelierLookback": 20,
        "GivebackPct": 0.40,
        "BreakEvenTriggerTicks": 10,
        "BreakEvenPlusTicks": 1,
        "MaxDailyLossUsd": 150,
        "MaxDailyProfitUsd": 500,
        "MaxDailyTrades": 6,
        "EnableDebugPrint": False,
        "Contracts": 1
    }
    ps_reasoning = {
        "RegimeMode": "Any — trades prior close reactions universally under intraday hours",
        "AllowRTH/ONH/ETH": "RTH only — restricted strictly to US main session to leverage volume liquidity",
        "StopTicks": "8 ticks ($40) — high-conviction tight scalp stop to capture precise pivot bounce",
        "TargetTicks": "20 ticks ($100) — quick profit target on prior close rejections",
        "ExitPolicy": "FixedRR — fixed risk-reward ratio to secure scalp wins instantly"
    }
    ps_xml = build_nt_xml(ps_params, "Prior Close Intraday Scalp (RTH Scoped)", ps_reasoning)
    with open(os.path.join(target_dir, "Prior_Session_Reaction_Close_Scalp.xml"), "w", encoding="utf-8") as f:
        f.write(ps_xml)
    print("Saved Prior_Session_Reaction_Close_Scalp.xml")

if __name__ == "__main__":
    main()
